### ISSUE TITLE
"Create screen" deletes existing code

### ISSUE THREAD

**Issue by unikolas** [theprotein/dynamics#280]
![image](https://cloud.githubusercontent.com/assets/906274/16210661/e95dfe1e-3745-11e6-9a6a-9af2e25f71f4.png)

**Comment by unikolas** [comment]
Hm. But code still in the file 
![image](https://cloud.githubusercontent.com/assets/906274/16210849/d2d9d0e0-3746-11e6-9a1f-92d259f8f84a.png)

**Comment by awinogradov** [comment]
fixed
