### ISSUE TITLE
don't see imported content in preview

### ISSUE THREAD

**Issue by unikolas** [theprotein/dynamics#283]
Imported project. Made in Sketch. 
"Save" has solved the problem. And cmd+R in preview window solves the problem.

![image](https://cloud.githubusercontent.com/assets/906274/16211338/97ea165e-3749-11e6-965d-d66749c2c5ac.png)

**Comment by unikolas** [comment]
UPD: After report everything works fine :| Bitch

**Comment by awinogradov** [comment]
fixed
